-- :require ./no-init-add-three-users.sql
INSERT INTO
    rides (
        id,
        location_from,
        location_to,
        tacking_place_at,
        created_by,
        driver,
        transport_limit
    )
VALUES
    (
        '123',
        'Graz',
        "Wien",
        '2044-11-26T15:18:26Z',
        'NnCaPHQLC9',
        'm6SYNABgAw',
        4
    ),
    (
        '222',
        "Tokyo",
        'Wien',
        '2044-12-24T15:18:30Z',
        'nmBSHcxyvn',
        'm6SYNABgAw',
        2
    ),
    (
        '321',
        'NYC',
        "Tokyo",
        '2044-11-28T15:18:30Z',
        'm6SYNABgAw',
        'NnCaPHQLC9',
        2
    );
