package common

const (
	ENV_NO_TLS               = "RS_NO_TLS"
	ENV_CORS_ORIGIN          = "RS_CORS_ORIGIN"
	ENV_TLS_KEY              = "RS_TLS_KEY"
	ENV_TLS_CERT             = "RS_TLS_CERT"
	ENV_DB_NAME              = "RS_DB_NAME"
	ENV_HOST_ADDR            = "RS_HOST_ADDR"
	ENV_WEB_APP_URL          = "RS_WEB_APP_URL"
	ENV_SECRET_AUTH_TOKEN    = "RS_SECRET_AUTH_TOKEN"
	ENV_GOOGLE_REDIRECT_URL  = "RS_GOOGLE_REDIRECT_URL"
	ENV_GOOGLE_CLIENT_ID     = "RS_GOOGLE_CLIENT_ID"
	ENV_GOOGLE_CLIENT_SECRET = "RS_GOOGLE_CLIENT_SECRET"
)
