package common

const (
	ENV_DB_NAME              = "RS_DB_NAME"
	ENV_HOST_ADDR            = "RS_HOST_ADDR"
	ENV_WEB_APP_URL          = "RS_WEB_APP_URL"
	ENV_SECRET_AUTH_TOKEN    = "RS_SECRET_AUTH_TOKEN"
	ENV_GOOGLE_REDIRECT_URL  = "RS_GOOGLE_REDIRECT_URL"
	ENV_GOOGLE_CLIENT_ID     = "RS_GOOGLE_CLIENT_ID"
	ENV_GOOGLE_CLIENT_SECRET = "RS_GOOGLE_CLIENT_SECRET"
)
