// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type User struct {
	ID           string
	Name         string
	Email        string
	Provider     string
	AccessToken  sql.NullString
	RefreshToken sql.NullString
}
