// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Ride struct {
	ID             int64  `json:"id"`
	LocationFrom   string `json:"locationFrom"`
	LocationTo     string `json:"locationTo"`
	TackingPlaceAt string `json:"tackingPlaceAt"`
	CreatedBy      string `json:"createdBy"`
	Driver         string `json:"driver"`
}

type RideParticipant struct {
	UserID string `json:"userId"`
	RideID int64  `json:"rideId"`
}

type User struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	Provider     string         `json:"provider"`
	AccessToken  sql.NullString `json:"accessToken"`
	RefreshToken sql.NullString `json:"refreshToken"`
}
