// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const usersCreate = `-- name: UsersCreate :one
INSERT INTO
    users (id, name, email, provider)
VALUES
    (?, ?, ?, ?) RETURNING id, name, email, provider, access_token, refresh_token, is_admin, is_blocked
`

type UsersCreateParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Provider string `json:"provider"`
}

// See sqlc docs for more information:
// https://docs.sqlc.dev/en/latest/tutorials/getting-started-sqlite.html#schema-and-queries
func (q *Queries) UsersCreate(ctx context.Context, arg UsersCreateParams) (User, error) {
	row := q.db.QueryRowContext(ctx, usersCreate,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Provider,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
		&i.AccessToken,
		&i.RefreshToken,
		&i.IsAdmin,
		&i.IsBlocked,
	)
	return i, err
}

const usersGetById = `-- name: UsersGetById :one
SELECT
    id, name, email, provider, access_token, refresh_token, is_admin, is_blocked
FROM
    users
WHERE
    id = ?
`

func (q *Queries) UsersGetById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, usersGetById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
		&i.AccessToken,
		&i.RefreshToken,
		&i.IsAdmin,
		&i.IsBlocked,
	)
	return i, err
}

const usersSetBlocked = `-- name: UsersSetBlocked :exec
UPDATE users
SET
    is_blocked = ?
WHERE
    id = ?
`

type UsersSetBlockedParams struct {
	IsBlocked bool   `json:"isBlocked"`
	ID        string `json:"id"`
}

func (q *Queries) UsersSetBlocked(ctx context.Context, arg UsersSetBlockedParams) error {
	_, err := q.db.ExecContext(ctx, usersSetBlocked, arg.IsBlocked, arg.ID)
	return err
}

const usersSetTokens = `-- name: UsersSetTokens :exec
UPDATE users
SET
    access_token = ?,
    refresh_token = ?
WHERE
    id = ?
`

type UsersSetTokensParams struct {
	AccessToken  sql.NullString `json:"accessToken"`
	RefreshToken sql.NullString `json:"refreshToken"`
	ID           string         `json:"id"`
}

func (q *Queries) UsersSetTokens(ctx context.Context, arg UsersSetTokensParams) error {
	_, err := q.db.ExecContext(ctx, usersSetTokens, arg.AccessToken, arg.RefreshToken, arg.ID)
	return err
}

const usersUpdateNameAndEmail = `-- name: UsersUpdateNameAndEmail :one
UPDATE users
SET
    name = ?,
    email = ?
WHERE
    id = ? RETURNING id, name, email, provider, access_token, refresh_token, is_admin, is_blocked
`

type UsersUpdateNameAndEmailParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	ID    string `json:"id"`
}

func (q *Queries) UsersUpdateNameAndEmail(ctx context.Context, arg UsersUpdateNameAndEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, usersUpdateNameAndEmail, arg.Name, arg.Email, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
		&i.AccessToken,
		&i.RefreshToken,
		&i.IsAdmin,
		&i.IsBlocked,
	)
	return i, err
}
