name: CI API Server
on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - "*"
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cd api-server && go build app/main.go
      - name: Test
        run: cd api-server && go test ./...
