name: Deploy API
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        env:
          ADDR_VPS_1: ${{ vars.ADDR_VPS_1 }}
          TARGET_NAME_API: ${{ vars.TARGET_NAME_API }}
          TARGET_KEY_API: ${{ secrets.TARGET_KEY_API }}
        run: ./deployment/ci/update-start.sh "$ADDR_VPS_1" "$TARGET_NAME_API" "$TARGET_KEY_API" "$GITHUB_SHA" && ./deployment/ci/update-wait-for-done.sh "$ADDR_VPS_1" "$TARGET_NAME_API" "$TARGET_KEY_API" "$GITHUB_JOB"
